<a href="https://colab.research.google.com/github/MohdAhmed627/Neural_Networks_for_Regression/blob/main/WindMill_Energy_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras

In [ ]:
from google.colab import files
import pandas as pd
uploaded = files.upload()
file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)

Saving energy.xlsx to energy.xlsx

In [ ]:
df.dtypes

AT    float64
V     float64
AP    float64
RH    float64
PE    float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB

In [ ]:
df.columns.tolist()

['AT', 'V', 'AP', 'RH', 'PE']

In [ ]:
df.head()

      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [ ]:
x = df.drop(columns = "PE")
y = df["PE"]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
sc = StandardScaler()
x_trian = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
from keras.layers import Dense,Input, Dropout

In [ ]:
model = Sequential()
model.add(Input(shape=(4,)))
model.add(Dense(units = 4, activation = "relu", kernel_initializer = "uniform"))
model.add(Dense(units = 8, activation = "relu", kernel_initializer = "uniform"))
model.add(Dropout(0.2))
model.add(Dense(units = 8, activation = "relu", kernel_initializer = "uniform"))
model.add(Dropout(0.2))
model.add(Dense(units = 16, activation = "relu", kernel_initializer = "uniform"))
model.add(Dropout(0.2))
model.add(Dense(
    units=1,
    activation="relu",
    kernel_initializer="uniform"
))

model.compile(
    optimizer="adam",
    loss="mean_squared_error",
    metrics = ["mae"]
)

In [ ]:
model.fit(x_train, y_train, batch_size = 32, epochs = 150 )

Epoch 1/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 113496.3438 - mae: 295.9235
Epoch 2/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 26026.6465 - mae: 131.4255
Epoch 3/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 25800.2695 - mae: 130.9893
Epoch 4/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 25246.0938 - mae: 129.1864
Epoch 5/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 24289.7949 - mae: 126.8302
Epoch 6/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23890.8594 - mae: 125.8430
Epoch 7/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 23084.0957 - mae: 123.5293
Epoch 8/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 22100.4570 - mae: 120.1082
Epoch 9/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 21255.7402 - mae: 116.8865
Epoch 10/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 20035.5742 - mae: 111.9914
Epoch 11/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19017.6953 - mae: 108.0640
Epoch 12/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 18355.6895 - mae: 105.8032
Epoch 13/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 16650.4316 - mae: 99.1825
Epoch 14/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 15302.2178 - mae: 95.1932
Epoch 15/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14981.2773 - mae: 93.6760
Epoch 16/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 15163.7686 - mae: 94.6308
Epoch 17/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 13037.2432 - mae: 88.1174
Epoch 18/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12118.9062 - mae: 84.9836
Epoch 19/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11916.2041 - mae: 83.5770
Epoch 20/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11882.6104 - mae: 84.0630
Epoch 21/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11845.2930 - mae: 83.7732
Epoch 22/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11339.1318 - mae: 81.8508
Epoch 23/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11011.6523 - mae: 80.6557
Epoch 24/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10845.2461 - mae: 80.4896
Epoch 25/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10706.5195 - mae: 79.5822
Epoch 26/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10310.3008 - mae: 78.4885
Epoch 27/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9826.4854 - mae: 77.0852
Epoch 28/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10098.5811 - mae: 78.0854
Epoch 29/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9691.3027 - mae: 76.4730
Epoch 30/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9475.4697 - mae: 75.3623
Epoch 31/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9003.6777 - mae: 73.5502
Epoch 32/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9273.6533 - mae: 75.0598
Epoch 33/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8640.6777 - mae: 72.5870
Epoch 34/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8279.7354 - mae: 70.4887
Epoch 35/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8281.9912 - mae: 71.2475
Epoch 36/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8178.6826 - mae: 71.0446
Epoch 37/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7809.2285 - mae: 69.0729
Epoch 38/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7601.9253 - mae: 68.2753
Epoch 39/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7426.3062 - mae: 67.7328
Epoch 40/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6983.5806 - mae: 65.7109
Epoch 41/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7090.2881 - mae: 66.5090
Epoch 42/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7005.6436 - mae: 65.9384
Epoch 43/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6848.2769 - mae: 65.1633
Epoch 44/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6626.0054 - mae: 64.1938
Epoch 45/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6584.1753 - mae: 64.2152
Epoch 46/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6380.0752 - mae: 63.3728
Epoch 47/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6396.5293 - mae: 63.1269
Epoch 48/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6248.2812 - mae: 62.0483
Epoch 49/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6206.6572 - mae: 62.2491
Epoch 50/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6050.1812 - mae: 61.8473
Epoch 51/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 6150.6353 - mae: 61.8573
Epoch 52/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5935.4336 - mae: 60.9146
Epoch 53/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5590.1279 - mae: 59.3521
Epoch 54/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5761.8271 - mae: 59.9032
Epoch 55/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5352.9961 - mae: 58.0555
Epoch 56/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 5485.7222 - mae: 58.7693
Epoch 57/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5198.2104 - mae: 57.0646
Epoch 58/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4921.4194 - mae: 55.5731
Epoch 59/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5003.6675 - mae: 56.0404
Epoch 60/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4705.4131 - mae: 54.3270
Epoch 61/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4864.4165 - mae: 55.0217
Epoch 62/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4779.9233 - mae: 54.7433
Epoch 63/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4714.7031 - mae: 54.3109
Epoch 64/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4390.3354 - mae: 52.4933
Epoch 65/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4540.8828 - mae: 52.9631
Epoch 66/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4284.7915 - mae: 51.7196
Epoch 67/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4350.3857 - mae: 52.6648
Epoch 68/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4185.0903 - mae: 51.2649
Epoch 69/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 4209.2783 - mae: 51.3163
Epoch 70/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 4047.7932 - mae: 50.1985
Epoch 71/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3925.3843 - mae: 49.7415
Epoch 72/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4033.6191 - mae: 50.4511
Epoch 73/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3951.0833 - mae: 49.8440
Epoch 74/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3872.0879 - mae: 49.5855
Epoch 75/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3780.5710 - mae: 48.8779
Epoch 76/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3811.8608 - mae: 49.0339
Epoch 77/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3680.7249 - mae: 48.1916
Epoch 78/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3630.0625 - mae: 47.6891
Epoch 79/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3560.9976 - mae: 47.4269
Epoch 80/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3560.4907 - mae: 47.5699
Epoch 81/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3590.1438 - mae: 47.6116
Epoch 82/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3584.1636 - mae: 47.3359
Epoch 83/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3424.6978 - mae: 46.4692
Epoch 84/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3451.5874 - mae: 47.0064
Epoch 85/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3370.6084 - mae: 46.1319
Epoch 86/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3304.0640 - mae: 45.8062
Epoch 87/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3292.2349 - mae: 45.5300
Epoch 88/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3334.6670 - mae: 46.0880
Epoch 89/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3219.6926 - mae: 45.2021
Epoch 90/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3247.1401 - mae: 45.2369
Epoch 91/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3260.5645 - mae: 45.3644
Epoch 92/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3269.7939 - mae: 45.3657
Epoch 93/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3152.5312 - mae: 44.6788
Epoch 94/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3157.5286 - mae: 44.6467
Epoch 95/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3210.1721 - mae: 44.9053
Epoch 96/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3185.1741 - mae: 44.8145
Epoch 97/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3207.6343 - mae: 44.9649
Epoch 98/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3158.1084 - mae: 44.6266
Epoch 99/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3106.5825 - mae: 44.0547
Epoch 100/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3165.2754 - mae: 44.8979
Epoch 101/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3118.9590 - mae: 44.0011
Epoch 102/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3156.5181 - mae: 44.6142
Epoch 103/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3181.5486 - mae: 44.6071
Epoch 104/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3205.1521 - mae: 44.7301
Epoch 105/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3152.7134 - mae: 44.6966
Epoch 106/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3092.4634 - mae: 44.0856
Epoch 107/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3080.3320 - mae: 43.8893
Epoch 108/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3134.9475 - mae: 44.3123
Epoch 109/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3148.4780 - mae: 44.5545
Epoch 110/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3064.8098 - mae: 43.9701
Epoch 111/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3081.6716 - mae: 44.0242
Epoch 112/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3088.3301 - mae: 44.0762
Epoch 113/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3093.4077 - mae: 44.0885
Epoch 114/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3082.2236 - mae: 43.7963
Epoch 115/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3169.1265 - mae: 44.3675
Epoch 116/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3070.3748 - mae: 43.8909
Epoch 117/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3010.6973 - mae: 43.5037
Epoch 118/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3093.2334 - mae: 44.2792
Epoch 119/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3018.3462 - mae: 43.5125
Epoch 120/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3066.7151 - mae: 43.7495
Epoch 121/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3133.1238 - mae: 44.1765
Epoch 122/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3083.9626 - mae: 44.1326
Epoch 123/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3049.6394 - mae: 43.8079
Epoch 124/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3054.0591 - mae: 43.6642
Epoch 125/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2980.8967 - mae: 43.2490
Epoch 126/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3016.1641 - mae: 43.3565
Epoch 127/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2977.4502 - mae: 43.3387
Epoch 128/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3034.9167 - mae: 43.6321
Epoch 129/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3044.6060 - mae: 43.4774
Epoch 130/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3073.0334 - mae: 43.8424
Epoch 131/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3064.6855 - mae: 43.7580
Epoch 132/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2990.3130 - mae: 43.0781
Epoch 133/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3043.3254 - mae: 43.4866
Epoch 134/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3143.7346 - mae: 44.6665
Epoch 135/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3045.6804 - mae: 43.5469
Epoch 136/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3058.5598 - mae: 43.5622
Epoch 137/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3095.0066 - mae: 43.9776
Epoch 138/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2990.3665 - mae: 43.2252
Epoch 139/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2958.5159 - mae: 42.9210
Epoch 140/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 2917.5938 - mae: 42.5902
Epoch 141/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3024.8367 - mae: 43.6584
Epoch 142/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3067.6924 - mae: 44.0167
Epoch 143/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3021.7004 - mae: 43.6239
Epoch 144/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3030.2292 - mae: 43.5839
Epoch 145/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2979.8279 - mae: 43.4520
Epoch 146/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2970.3962 - mae: 43.0896
Epoch 147/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2941.3159 - mae: 43.1156
Epoch 148/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3039.7144 - mae: 43.4081
Epoch 149/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2998.8772 - mae: 43.2911
Epoch 150/150
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3098.4448 - mae: 44.0066

In [ ]:
y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

In [ ]:
from sklearn.metrics import accuracy_score, mean_squared_error

In [ ]:
print("MSE of train data:", mean_squared_error(y_train, y_pred_train))
print("MSE of test data:", mean_squared_error(y_test,y_pred_test))

MSE of train data: 35.49737034898981
MSE of test data: 566.0738328601645